### ISSUE TITLE
Please specify the version of package...

### ISSUE THREAD

**Issue by yagom** [IBM-Swift/Kitura-CORS#25]
I **wasted** my time about half a day cause of Swift Package Manager dependencies...
No one let me know the **latest version of 'Kitura-CORS'** package in this github page. So i tried lots of times to build but fails every time. Wrong package version and dependency...
Please tell us the latest version of this package in the github **README**... to prevent wasting time...

**Comment by irar2** [comment]
Hi @yagom, do you mean you would like to see the latest tag in the README?

**Comment by yagom** [comment]
Thanks for reply, @irar2 
Yes, if the **tag** you said is same with the **latest version** of [this page](https://swiftpkgs.ng.bluemix.net/package/IBM-Swift/Kitura-CORS)
And i know those are almost always same, but seldomly different.

**Comment by irar2** [comment]
Hi @yagom, thanks, I understand now. 
Tags are the version numbers of the form `major.minor.micro`. You need to specify in Package.dependencies the major and the minor version numbers. 
In order to get the latest tag, go to the github page of the repository, click on the `branch` button, choose the branch `master`, and then click the `tag` tab. You will see all the available tags. For the latest version, just choose the highest tag.
![screen shot 2017-02-13 at 9 01 36](https://cloud.githubusercontent.com/assets/16818592/22877796/c0883b76-f1df-11e6-9509-772edc1fd625.png)

**Comment by yagom** [comment]
It's so kind of you @irar2 
Thanks for your guidance.
